global:
    scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"] # Prometheus itself

    - job_name: "coca-backend"
      metrics_path: "/actuator/prometheus" # Spring Boot Actuator Prometheus endpoint
      static_configs:
          - targets: ["backend:8080"] # 'backend' is the service name in docker-compose
      scheme: http
      bearer_token: "__MONITORING_TOKEN__"
